# Generated by Django 4.2.5 on 2023-09-26 12:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesTaches', '0003_user_alter_task_schedule_date_task_utilisateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ListeDiffusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listeName', models.CharField(max_length=30)),
                ('email', models.ManyToManyField(related_name='listes', to='lesTaches.email')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='utilisateur',
        ),
        migrations.AlterField(
            model_name='task',
            name='schedule_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 3, 14, 56, 6, 7502)),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='email',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='lesTaches.utilisateur'),
        ),
    ]
