# Generated by Django 4.2.5 on 2023-09-26 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesTaches', '0004_email_listediffusion_utilisateur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='prenom',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='schedule_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 3, 15, 12, 49, 523244)),
        ),
    ]
